name: CheckStyle_Comments
on: pull_request

jobs:
  phpmd_checkstyle:
    name: CheckStyle Comments

    runs-on: ubuntu-latest
    env:
      php: "7.4"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer:v2, cs2pr, phpmd

      - name: "Install locked dependencies from composer.lock"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: no namespace, local phpmd bin
        run: vendor/bin/phpmd test CheckStyleRenderer naming,cleancode | cs2pr --graceful-warnings

      - name: no namespace, global phpmd bin
        run: phpmd test CheckStyleRenderer naming,cleancode | cs2pr --graceful-warnings

      - name: namespaced, local phpmd bin
        run: vendor/bin/phpmd test MyRenderers\\CheckStyleRenderer naming,cleancode | cs2pr --graceful-warnings

      - name: namespaced, global phpmd bin
        run: phpmd test MyRenderers\\CheckStyleRenderer naming,cleancode | cs2pr --graceful-warnings
