name: Github_Renderer_On_Root_Folder
on: push

jobs:
  phpmd_root_folder:
    name: Local bin, renderer on project root (Lukas Bestle's Github Renderer on project root)

    runs-on: ubuntu-latest
    env:
      php: "7.4"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer:v2

      - name: "Install locked dependencies from composer.lock"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: Run Local PHPMD binary
        run: src/bin/phpmd test GitHubRenderer naming --ignore-violations-on-exit

  phpmd_global_binary:
    name: Global bin, namespaced renderer (Lukas Bestle's Github Renderer)

    runs-on: ubuntu-latest
    env:
      php: "7.4"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer:v2, phpmd

      - name: "Install locked dependencies from composer.lock"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: Run Global PHPMD binary
        run: phpmd test GitHubRenderer naming --ignore-violations-on-exit
